### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by xTibor** [xTibor/cppjpeg#1]
* [ ] Cleanup (DU/MCU code is messy), more idiomatic C++
* [ ] Fix Serenity's image plugin infrastructure
* [ ] LibGfx YCbCr support (with different profiles?)
* [ ] Rewrite to AK
